// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package routers

import (
	"github.com/google/wire"
	"melon-service/controllers"
	"melon-service/databases"
	"melon-service/interfaces"
	"melon-service/repositories"
	"melon-service/services"
)

// Injectors from wire.go:

func InitializeUserController(db *databases.DB) controllers.UserController {
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	userController := controllers.NewUserController(userService)
	return userController
}

// wire.go:

var userServiceRepoSet = wire.NewSet(controllers.NewUserController, wire.Bind(new(interfaces.IUserService), new(services.UserService)), services.NewUserService)

var userRepositorySet = wire.NewSet(wire.Bind(new(interfaces.IUserRepository), new(repositories.UserRepository)), repositories.NewUserRepository)
